# Generated by Django 4.2.29 on 2026-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentrequest_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
