# Generated by Django 4.2.29 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointmentrequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='country',
            field=models.CharField(choices=[('CD', 'Democratic Republic of the Congo'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('UG', 'Uganda'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('CG', 'Republic of the Congo'), ('ZA', 'South Africa'), ('BE', 'Belgium'), ('CN', 'China'), ('FR', 'France'), ('CA', 'Canada'), ('US', 'United States'), ('GB', 'United Kingdom'), ('ZZ', 'Other / Not listed')], default='CD', max_length=2),
        ),
    ]
