# Generated by Django 4.2.29 on 2026-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointmentrequest_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='office',
            field=models.CharField(choices=[('kinshasa', 'Kinshasa'), ('bukavu', 'Bukavu')], default='kinshasa', max_length=20),
        ),
    ]
